"""update company weekly report model

Revision ID: 17af6692dee5
Revises: fa87b3af709d
Create Date: 2025-04-16 19:55:50.300481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17af6692dee5'
down_revision = 'fa87b3af709d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_weekly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_work', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('submitter', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('submit_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archive_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_weekly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('archive_time')
        batch_op.drop_column('archived')
        batch_op.drop_column('submit_time')
        batch_op.drop_column('submitter')
        batch_op.drop_column('submitted')
        batch_op.drop_column('next_plan')
        batch_op.drop_column('current_work')

    # ### end Alembic commands ###
