"""Add named constraints

Revision ID: 4b0c9a9b2bd9
Revises: 
Create Date: 2025-04-21 14:09:17.095336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0c9a9b2bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_plan', schema=None) as batch_op:
        batch_op.alter_column('plan_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_time_plan_plan_name', ['plan_name'])  # 添加约束名称

    with op.batch_alter_table('time_plan_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.alter_column('plan_node',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('responsible_leader',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_time_plan_detail_plan_id', 'time_plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_plan', schema=None) as batch_op:
        batch_op.drop_constraint('uq_time_plan_plan_name', type_='unique')  # 对应删除约束
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('plan_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
