"""Add department_submitted column

Revision ID: fa87b3af709d
Revises: 
Create Date: 2025-04-16 14:14:23.019710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa87b3af709d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_weekly_report')
    with op.batch_alter_table('personal_weekly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_weekly_report', schema=None) as batch_op:
        batch_op.drop_column('department_submitted')

    op.create_table('department_weekly_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('submitter', sa.VARCHAR(length=20), nullable=True),
    sa.Column('submit_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
