name: Auto Deploy
on:
  push:
    branches: [main]  # 监听的分支
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH to Aliyun
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USER }}
        key: ${{ secrets.ALIYUN_SSH_KEY }}
        script: |
          cd /var/www/project
          git pull origin main
          npm install
          npm run build
          pm2 restart app.js 